language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  fqdn: jamielau.me
  on:
    branch: master

dist: bionic
sudo: false
